name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 Triggered by a ${{ github.event_name }} event."

      - run: echo "🐧 Running on ${{ runner.os }} hosted by GitHub."

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: List files
        run: ls "${{ github.workspace }}"

      - run: echo "🍏 Job status is ${{ job.status }}."

  check-pull-request-event:
    runs-on: ubuntu-latest

    steps:
      - name: Confirm pull request event
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This is a pull request event."

      - name: Handle non-pull-request event
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "This is not a pull request event."

  check-merge-event:
    runs-on: ubuntu-latest

    steps:
      - name: Confirm merged pull request
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
        run: echo "This pull request was merged."

      - name: Handle non-merged event
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged != true }}
        run: echo "This was not a merged pull request."